### ISSUE TITLE
Should disable Eslint/Prettier on code generation

### ISSUE THREAD

**Issue by jellydn** [codenothing/proto-client#1]
# Context

Thank you for your awesome. I'm trying to integrated proto-client on my [jellydn/grpc-demo-monorepo: NodeJS/Go + GRPC/Connect + NextJS](https://github.com/jellydn/grpc-demo-monorepo) then got error with Prettier. Then I have to add the `gen` folder to Eslint/Prettier ignore https://github.com/jellydn/grpc-demo-monorepo/commit/a4a66e1bdb22ecf544298b96c46d371a61ec266c

# What

- Add disable ESlint & Prettier on top of the file

# Why

- This is common practise on code generation to seamless/avoid error

# How

Below is the example from connect-web. I think it should work the same way for proto-client.

```typescript
// @generated by protoc-gen-connect-web v0.3.1 with parameter "target=ts"
// @generated from file protos/hello.proto (package helloworld, syntax proto3)

/* eslint-disable */

/* @ts-nocheck */
```

**Comment by codenothing** [comment]
You should be able to add the generated files to your `.prettierignore` and `.eslintignore` files

**Comment by jellydn** [comment]
> You should be able to add the generated files to your `.prettierignore` and `.eslintignore` files

Yes, that's what I did.

**Comment by jellydn** [comment]
FYI 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/870029/202944859-bec7c5aa-bf03-4e6c-9004-65d5ff5e3d5b.png">

**Comment by codenothing** [comment]
Oh I see now. I think I would prefer to not add any linter specific commands. Don't want to have to add a new ignore command for any new linter/formatter that comes out in the future. Adding the gen folder to a repos ignore files is a good solution for now.
